[package]
name = "coviz"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
description = "Source code logic and call graph visualizer for Go and Rust."
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/coviz"
homepage = "https://github.com/christiandoxa/coviz"
repository = "https://github.com/christiandoxa/coviz"
keywords = ["callgraph", "visualization", "golang", "rust", "tree-sitter"]
categories = ["command-line-utilities", "development-tools"]
exclude = [
    ".github/",
    ".idea/",
    "target/",
]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
rayon = "1.12.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tree-sitter = "0.26.8"
tree-sitter-go = "0.25.0"
tree-sitter-rust = "0.24.2"
walkdir = "2.5.0"
